//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionWin.ServicioArticulos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articulo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Articulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioArticulos.ServicioArticulosSoap")]
    public interface ServicioArticulosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarArticuloResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarArticulo", ReplyAction="*")]
        PresentacionWin.ServicioArticulos.BuscarArticuloResponse BuscarArticulo(PresentacionWin.ServicioArticulos.BuscarArticuloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarArticuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarArticulo", Namespace="http://tempuri.org/", Order=0)]
        public PresentacionWin.ServicioArticulos.BuscarArticuloRequestBody Body;
        
        public BuscarArticuloRequest() {
        }
        
        public BuscarArticuloRequest(PresentacionWin.ServicioArticulos.BuscarArticuloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarArticuloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pCodigo;
        
        public BuscarArticuloRequestBody() {
        }
        
        public BuscarArticuloRequestBody(int pCodigo) {
            this.pCodigo = pCodigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarArticuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarArticuloResponse", Namespace="http://tempuri.org/", Order=0)]
        public PresentacionWin.ServicioArticulos.BuscarArticuloResponseBody Body;
        
        public BuscarArticuloResponse() {
        }
        
        public BuscarArticuloResponse(PresentacionWin.ServicioArticulos.BuscarArticuloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarArticuloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PresentacionWin.ServicioArticulos.Articulo BuscarArticuloResult;
        
        public BuscarArticuloResponseBody() {
        }
        
        public BuscarArticuloResponseBody(PresentacionWin.ServicioArticulos.Articulo BuscarArticuloResult) {
            this.BuscarArticuloResult = BuscarArticuloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioArticulosSoapChannel : PresentacionWin.ServicioArticulos.ServicioArticulosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioArticulosSoapClient : System.ServiceModel.ClientBase<PresentacionWin.ServicioArticulos.ServicioArticulosSoap>, PresentacionWin.ServicioArticulos.ServicioArticulosSoap {
        
        public ServicioArticulosSoapClient() {
        }
        
        public ServicioArticulosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioArticulosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioArticulosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioArticulosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PresentacionWin.ServicioArticulos.BuscarArticuloResponse PresentacionWin.ServicioArticulos.ServicioArticulosSoap.BuscarArticulo(PresentacionWin.ServicioArticulos.BuscarArticuloRequest request) {
            return base.Channel.BuscarArticulo(request);
        }
        
        public PresentacionWin.ServicioArticulos.Articulo BuscarArticulo(int pCodigo) {
            PresentacionWin.ServicioArticulos.BuscarArticuloRequest inValue = new PresentacionWin.ServicioArticulos.BuscarArticuloRequest();
            inValue.Body = new PresentacionWin.ServicioArticulos.BuscarArticuloRequestBody();
            inValue.Body.pCodigo = pCodigo;
            PresentacionWin.ServicioArticulos.BuscarArticuloResponse retVal = ((PresentacionWin.ServicioArticulos.ServicioArticulosSoap)(this)).BuscarArticulo(inValue);
            return retVal.Body.BuscarArticuloResult;
        }
    }
}
