//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PresentacionWin.WSArticulos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioArticulosSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioArticulos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarArticuloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarArticuloOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioArticulos() {
            this.Url = global::PresentacionWin.Properties.Settings.Default.PresentacionWin_WSArticulos_ServicioArticulos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarArticuloCompletedEventHandler BuscarArticuloCompleted;
        
        /// <remarks/>
        public event AltaArticuloCompletedEventHandler AltaArticuloCompleted;
        
        /// <remarks/>
        public event BajaArticuloCompletedEventHandler BajaArticuloCompleted;
        
        /// <remarks/>
        public event ModificarArticuloCompletedEventHandler ModificarArticuloCompleted;
        
        /// <remarks/>
        public event ListarArticuloCompletedEventHandler ListarArticuloCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarArticulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Articulo BuscarArticulo(int pCodigo) {
            object[] results = this.Invoke("BuscarArticulo", new object[] {
                        pCodigo});
            return ((Articulo)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarArticuloAsync(int pCodigo) {
            this.BuscarArticuloAsync(pCodigo, null);
        }
        
        /// <remarks/>
        public void BuscarArticuloAsync(int pCodigo, object userState) {
            if ((this.BuscarArticuloOperationCompleted == null)) {
                this.BuscarArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarArticuloOperationCompleted);
            }
            this.InvokeAsync("BuscarArticulo", new object[] {
                        pCodigo}, this.BuscarArticuloOperationCompleted, userState);
        }
        
        private void OnBuscarArticuloOperationCompleted(object arg) {
            if ((this.BuscarArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarArticuloCompleted(this, new BuscarArticuloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaArticulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaArticulo(Articulo art) {
            this.Invoke("AltaArticulo", new object[] {
                        art});
        }
        
        /// <remarks/>
        public void AltaArticuloAsync(Articulo art) {
            this.AltaArticuloAsync(art, null);
        }
        
        /// <remarks/>
        public void AltaArticuloAsync(Articulo art, object userState) {
            if ((this.AltaArticuloOperationCompleted == null)) {
                this.AltaArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaArticuloOperationCompleted);
            }
            this.InvokeAsync("AltaArticulo", new object[] {
                        art}, this.AltaArticuloOperationCompleted, userState);
        }
        
        private void OnAltaArticuloOperationCompleted(object arg) {
            if ((this.AltaArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaArticulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaArticulo(Articulo art) {
            this.Invoke("BajaArticulo", new object[] {
                        art});
        }
        
        /// <remarks/>
        public void BajaArticuloAsync(Articulo art) {
            this.BajaArticuloAsync(art, null);
        }
        
        /// <remarks/>
        public void BajaArticuloAsync(Articulo art, object userState) {
            if ((this.BajaArticuloOperationCompleted == null)) {
                this.BajaArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaArticuloOperationCompleted);
            }
            this.InvokeAsync("BajaArticulo", new object[] {
                        art}, this.BajaArticuloOperationCompleted, userState);
        }
        
        private void OnBajaArticuloOperationCompleted(object arg) {
            if ((this.BajaArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarArticulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarArticulo(Articulo art) {
            this.Invoke("ModificarArticulo", new object[] {
                        art});
        }
        
        /// <remarks/>
        public void ModificarArticuloAsync(Articulo art) {
            this.ModificarArticuloAsync(art, null);
        }
        
        /// <remarks/>
        public void ModificarArticuloAsync(Articulo art, object userState) {
            if ((this.ModificarArticuloOperationCompleted == null)) {
                this.ModificarArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarArticuloOperationCompleted);
            }
            this.InvokeAsync("ModificarArticulo", new object[] {
                        art}, this.ModificarArticuloOperationCompleted, userState);
        }
        
        private void OnModificarArticuloOperationCompleted(object arg) {
            if ((this.ModificarArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarArticuloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarArticulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Articulo[] ListarArticulo() {
            object[] results = this.Invoke("ListarArticulo", new object[0]);
            return ((Articulo[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarArticuloAsync() {
            this.ListarArticuloAsync(null);
        }
        
        /// <remarks/>
        public void ListarArticuloAsync(object userState) {
            if ((this.ListarArticuloOperationCompleted == null)) {
                this.ListarArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarArticuloOperationCompleted);
            }
            this.InvokeAsync("ListarArticulo", new object[0], this.ListarArticuloOperationCompleted, userState);
        }
        
        private void OnListarArticuloOperationCompleted(object arg) {
            if ((this.ListarArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarArticuloCompleted(this, new ListarArticuloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Articulo {
        
        private int codigoField;
        
        private string nombreField;
        
        private decimal precioField;
        
        /// <comentarios/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void BuscarArticuloCompletedEventHandler(object sender, BuscarArticuloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarArticuloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarArticuloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Articulo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Articulo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void AltaArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void BajaArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ModificarArticuloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ListarArticuloCompletedEventHandler(object sender, ListarArticuloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarArticuloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarArticuloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Articulo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Articulo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591